service: 
  name: PlanrrDesiro

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  profile: default
  
  vpc:
    securityGroupIds:
      - sg-0ded318cb0545e951
    subnetIds:
      - subnet-1c0fd146
      - subnet-1c0fd146
      - subnet-1c0fd146

  apiKeys:
    - Sprinter

functions:

  stationArrivals:
    handler: index.handler
    events:
      - http: 
          path: /station/{stationCode}/arrivals
          method: GET
          private: true
          request:
            parameters:
              paths:
                stationCode: true
      - http: 
          path: /station/{stationCode}/arrivals/{year}/{month}/{day}/{time}
          method: GET
          private: true
          request:
            parameters:
              paths:
                stationCode: true
                year: false
                month: false
                day: false
                time: false

  stationDepartures:
    handler: index.handler
    events:
      - http: 
          path: /station/{stationCode}/departures
          method: GET
          private: true
          request:
            parameters:
              paths:
                stationCode: true
      - http: 
          path: /station/{stationCode}/departures/{year}/{month}/{day}/{time}
          method: GET
          private: true
          request:
            parameters:
              paths:
                stationCode: true
                year: true
                month: true
                day: true
                time: true

  trainService:
    handler: index.handler
    events:
      - http: 
          path: /train/{uid}/{year}/{month}/{day}
          method: GET
          private: true

custom:

  customDomain:
    domainName: api.planrr.app
    certificateName:  api.planrr.app
    basePath: ''
    stage: ${self:provider.stage}
    endpointType: regional
    createRoute53Record: true

plugins:
  - serverless-offline
  - serverless-domain-manager