service: 
  name: PlanrrDesiro

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

functions:

  # app:
  #   handler: index.handler
  #   events:
  #     - http: ANY /

  stationArrivals:
    handler: index.handler
    events:
      - http: 'GET /station/{stationCode}/arrivals'

  stationDepartures:
    handler: index.handler
    events:
      - http: 'GET /station/{stationCode}/departures'

  trainService:
    handler: index.handler
    events:
      - http: 'GET /train/{uid}/{year}/{month}/{day}'

plugins:
  - serverless-offline